FROM scratch
MAINTAINER build by stone,blog  http://man.linuxnb.com

#http://download.linuxnb.com/centos/centos-7-docker.tar.xz
#ADD http://download.linuxnb.com/centos/centos-7-docker.tar.xz /

ADD centos-7-docker.tar.xz /

LABEL name="CentOS Base Image" \
    version="7.4" \
    vendor="CentOS" \
    license="GPLv2" \
    build-date="20171108"

CMD ["/bin/bash"]
